export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_RESET = 'ORDER_RESET';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
