export const ADD_TO_CART1 = 'ADD_TO_CART1';
export const ADD_ALL_TO_CART1 = 'ADD_ALL_TO_CART1';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const UPDATE_CART1_ITEM = 'UPDATE_CART1_ITEM';
export const DELETE_FROM_CART1 = 'DELETE_FROM_CART1';
export const DELETE_ALL_FROM_CART1 = 'DELETE_ALL_FROM_CART1';
