export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_ALL_TO_CART = 'ADD_ALL_TO_CART';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CHANGE_WEIGHT = 'CHANGE_WEIGHT';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const DELETE_ALL_FROM_CART = 'DELETE_ALL_FROM_CART';
