export const EXPENSE_REQUEST = 'EXPENSE_REQUEST';
export const EXPENSE_FAIL = 'EXPENSE_FAIL';
export const EXPENSE_RESET = 'EXPENSE_RESET';

export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS';
export const UPDATE_EXPENSE_SUCCESS = 'UPDATE_EXPENSE_SUCCESS';
