export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';
export const PRODUCT_RESET = 'PRODUCT_RESET';

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
