export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_FAIL = 'TRANSACTION_FAIL';
export const TRANSACTION_RESET = 'TRANSACTION_RESET';

export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
