export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const BOOKING_FAIL = 'BOOKING_FAIL';
export const BOOKING_RESET = 'BOOKING_RESET';

export const GET_BOOKINGS_SUCCESS = 'GET_BOOKINGS_SUCCESS';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
