export const INVENTORY_REQUEST = 'INVENTORY_REQUEST';
export const INVENTORY_FAIL = 'INVENTORY_FAIL';
export const INVENTORY_RESET = 'INVENTORY_RESET';

export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const GET_INVENTORIES_SUCCESS = 'GET_INVENTORIES_SUCCESS';
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
