export const STOCK_REQUEST = 'STOCK_REQUEST';
export const STOCK_FAIL = 'STOCK_FAIL';
export const STOCK_RESET = 'STOCK_RESET';

export const CREATE_STOCK_SUCCESS = 'CREATE_STOCK_SUCCESS';
export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';
export const GET_STOCK_SUCCESS = 'GET_STOCK_SUCCESS';
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS';
