export const DEAL_REQUEST = 'DEAL_REQUEST';
export const DEAL_FAIL = 'DEAL_FAIL';
export const DEAL_RESET = 'DEAL_RESET';

export const CREATE_DEAL_SUCCESS = 'CREATE_DEAL_SUCCESS';
export const GET_DEALS_SUCCESS = 'GET_DEALS_SUCCESS';
export const GET_DEAL_SUCCESS = 'GET_DEAL_SUCCESS';
export const UPDATE_DEAL_SUCCESS = 'UPDATE_DEAL_SUCCESS';
